# Generated by Django 5.2.4 on 2025-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_studymaterial_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='previews/'),
        ),
    ]
