# Generated by Django 5.2.4 on 2025-07-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_rating_options_alter_rating_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='materials.studymaterial'),
        ),
    ]
